baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'rosesori'
theme = 'hugo-theme-stack'

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/rosesori"

[social.params]
icon = "brand-github"
